using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PlayerListModel 
{
    [RealtimeProperty(1, true, true)]
    private string _playerList;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PlayerListModel : RealtimeModel {
    public string playerList {
        get {
            return _cache.LookForValueInCache(_playerList, entry => entry.playerListSet, entry => entry.playerList);
        }
        set {
            if (this.playerList == value) return;
            _cache.UpdateLocalCache(entry => { entry.playerListSet = true; entry.playerList = value; return entry; });
            InvalidateReliableLength();
            FirePlayerListDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PlayerListModel model, T value);
    public event PropertyChangedHandler<string> playerListDidChange;
    
    private struct LocalCacheEntry {
        public bool playerListSet;
        public string playerList;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        PlayerList = 1,
    }
    
    public PlayerListModel() : this(null) {
    }
    
    public PlayerListModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FirePlayerListDidChange(string value) {
        try {
            playerListDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteStringLength((uint)PropertyID.PlayerList, _playerList);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playerListSet) {
                length += WriteStream.WriteStringLength((uint)PropertyID.PlayerList, entry.playerList);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteString((uint)PropertyID.PlayerList, _playerList);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playerListSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.playerListSet) {
                stream.WriteString((uint)PropertyID.PlayerList, entry.playerList);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.PlayerList: {
                    string previousValue = _playerList;
                    _playerList = stream.ReadString();
                    bool playerListExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.playerListSet);
                    if (!playerListExistsInChangeCache && _playerList != previousValue) {
                        FirePlayerListDidChange(_playerList);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _playerList = playerList;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
