using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TeamModel
{
    [RealtimeProperty(1, true, true)]
    private int _playerCount = 0;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TeamModel : RealtimeModel {
    public int playerCount {
        get {
            return _cache.LookForValueInCache(_playerCount, entry => entry.playerCountSet, entry => entry.playerCount);
        }
        set {
            if (this.playerCount == value) return;
            _cache.UpdateLocalCache(entry => { entry.playerCountSet = true; entry.playerCount = value; return entry; });
            InvalidateReliableLength();
            FirePlayerCountDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TeamModel model, T value);
    public event PropertyChangedHandler<int> playerCountDidChange;
    
    private struct LocalCacheEntry {
        public bool playerCountSet;
        public int playerCount;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        PlayerCount = 1,
    }
    
    public TeamModel() : this(null) {
    }
    
    public TeamModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FirePlayerCountDidChange(int value) {
        try {
            playerCountDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.PlayerCount, (uint)_playerCount);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playerCountSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.PlayerCount, (uint)entry.playerCount);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.PlayerCount, (uint)_playerCount);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playerCountSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.playerCountSet) {
                stream.WriteVarint32((uint)PropertyID.PlayerCount, (uint)entry.playerCount);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.PlayerCount: {
                    int previousValue = _playerCount;
                    _playerCount = (int)stream.ReadVarint32();
                    bool playerCountExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.playerCountSet);
                    if (!playerCountExistsInChangeCache && _playerCount != previousValue) {
                        FirePlayerCountDidChange(_playerCount);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _playerCount = playerCount;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
